### ISSUE TITLE
macOS에서 yarn build 실행시 뜨는 에러.

### ISSUE THREAD

**Issue by khw7096** [studio2l/elo#10]
npm install --global yarn

명령어 이후

```
hanwoongui-iMac:elo woong$ yarn build
yarn run v1.16.0
warning package.json: License should be a valid SPDX license expression
error Command "build" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by kybin** [comment]
맥에서 빌드가 안 될 이유가 없을것 같은데 다시 해봐주실수 있나요?

**Comment by khw7096** [comment]
외부 노트북에는 많은걸 깔고 싶지 않아서.. 집에가서 다시한번 해볼께요.  imac으로

**Comment by khw7096** [comment]
다시 테스트
```bash
$ sudo npm install --global yarn
$ sudo npm install -g npm # 버전을 6.10으로 올리라고 메시지가뜸.
```

**Comment by khw7096** [comment]
다시 해봐도 같은 에러.

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/1149996/60706500-8fc29f80-9f44-11e9-9ca4-ec20cd7dd5c1.png">

**Comment by khw7096** [comment]
`yarn build` 라는 명령어는 범용 명령어가 아닌것 같아요. build를 찾지못한다고 하여...

**Comment by khw7096** [comment]
https://yarnpkg.com/en/docs/cli/run  요기 메뉴얼을 읽어봐도 build 명령어는 없네요. Readme.md 정보가 잘못된듯해요.

**Comment by kybin** [comment]
윈도우즈랑 리눅스에서 문제없이 빌드되고 있어서.. 한번 살펴볼게요.

**Comment by kybin** [comment]
아 node_builder 인가를 깔았던것 같기도 한데. npm start는 잘 되는 상힁인거죠?

**Comment by khw7096** [comment]
npm start를 하면 tsc 를 깔라고 나오네용.

아래 명령어부터..
```bash
$ npm i tsc
```

**Comment by kybin** [comment]
npm install --global typescript 해보세요

**Comment by khw7096** [comment]
npm install --global typescript 는 했어요. 그다음 npm start 를 하면 아래 메시지가 떠요.

```bash
hanwoongui-MacBook:elo hanwoongkim$ npm start

> elo@0.0.2 prestart /Users/hanwoongkim/elo
> tsc

error TS5014: Failed to parse file 'tsconfig.json': Unexpected token ] in JSON at position 29.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elo@0.0.2 prestart: `tsc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the elo@0.0.2 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hanwoongkim/.npm/_logs/2019-07-05T10_07_02_188Z-debug.log
```

**Comment by khw7096** [comment]
어떤 형태로 배포를 하는지 큰 구조를 모르니.. 에러를 만났을 때 당황스럽네요. 하하!!

**Comment by khw7096** [comment]
하지만 yarn build 를 했을 때.. 이제는 에러가 나지만.. 그래도 몬가 지나가요.

```
hanwoongui-MacBook:elo hanwoongkim$ yarn build
yarn run v1.16.0
warning package.json: License should be a valid SPDX license expression
$ /Users/hanwoongkim/elo/node_modules/.bin/build
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
  • electron-builder version=20.39.0
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=darwin arch=x64 electron=4.1.1 appOutDir=dist/mac
  • default Electron icon is used reason=application icon is not set
Error: Application entry file "main.js" in the "/Users/hanwoongkim/elo/dist/mac/elo.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/Users/hanwoongkim/elo/node_modules/app-builder-lib/out/asar/asarFileChecker.js:44:14)
    at /Users/hanwoongkim/elo/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:30:4
    at Generator.next (<anonymous>)
    at /Users/hanwoongkim/elo/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at _checkFileInArchive (/Users/hanwoongkim/elo/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:36:17)
    at checkFileInArchive (/Users/hanwoongkim/elo/node_modules/app-builder-lib/out/asar/asarFileChecker.js:40:30)
    at /Users/hanwoongkim/elo/node_modules/app-builder-lib/src/platformPackager.ts:409:13
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.checkFileInPackage (/Users/hanwoongkim/elo/node_modules/app-builder-lib/src/platformPackager.ts:406:110)
    at /Users/hanwoongkim/elo/node_modules/app-builder-lib/src/platformPackager.ts:460:16
    at Generator.next (<anonymous>)
    at /Users/hanwoongkim/elo/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at MacPackager.sanityCheckPackage (/Users/hanwoongkim/elo/node_modules/app-builder-lib/src/platformPackager.ts:446:92)
    at /Users/hanwoongkim/elo/node_modules/app-builder-lib/src/platformPackager.ts:249:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at MacPackager.doPack (/Users/hanwoongkim/elo/node_modules/app-builder-lib/src/platformPackager.ts:167:165)
    at /Users/hanwoongkim/elo/node_modules/app-builder-lib/src/macPackager.ts:88:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/hanwoongkim/elo/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/hanwoongkim/elo/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/hanwoongkim/elo/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/hanwoongkim/elo/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at Packager.doBuild (/Users/hanwoongkim/elo/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/hanwoongkim/elo/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/hanwoongkim/elo/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/hanwoongkim/elo/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
    at Packager._build (/Users/hanwoongkim/elo/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/hanwoongkim/elo/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (/Users/hanwoongkim/elo/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/hanwoongkim/elo/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/hanwoongkim/elo/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/Users/hanwoongkim/elo/node_modules/electron-builder/src/cli/cli.ts:46:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
hanwoongui-MacBook:elo hanwoongkim$
```

**Comment by khw7096** [comment]
노트북 베터리가 다 되어가네요 오늘은 여기까지!

**Comment by kybin** [comment]
네 나중에 같이해보죠

**Comment by khw7096** [comment]
npm install 을 다시 해봄..

에러

```
Error: Application entry file "main.js" in the "/Users/hanwoongkim/elo/dist/mac/elo.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/Users/hanwoongkim/elo/node_modules/app-builder-lib/out/asar/asarFileChecker.js:44:14)
    at /Users/hanwoongkim/elo/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:30:4
    at Generator.next (<anonymous>)
    at /Users/hanwoongkim/elo/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at _checkFileInArchive (/Users/hanwoongkim/elo/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:36:17)
    at checkFileInArchive (/Users/hanwoongkim/elo/node_modules/app-builder-lib/out/asar/asarFileChecker.js:40:30)
    at /Users/hanwoongkim/elo/node_modules/app-builder-lib/src/platformPackager.ts:409:13
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.checkFileInPackage (/Users/hanwoongkim/elo/node_modules/app-builder-lib/src/platformPackager.ts:406:110)
    at /Users/hanwoongkim/elo/node_modules/app-builder-lib/src/platformPackager.ts:460:16
    at Generator.next (<anonymous>)
    at /Users/hanwoongkim/elo/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at MacPackager.sanityCheckPackage (/Users/hanwoongkim/elo/node_modules/app-builder-lib/src/platformPackager.ts:446:92)
    at /Users/hanwoongkim/elo/node_modules/app-builder-lib/src/platformPackager.ts:249:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at MacPackager.doPack (/Users/hanwoongkim/elo/node_modules/app-builder-lib/src/platformPackager.ts:167:165)
    at /Users/hanwoongkim/elo/node_modules/app-builder-lib/src/macPackager.ts:88:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/hanwoongkim/elo/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/hanwoongkim/elo/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/hanwoongkim/elo/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/hanwoongkim/elo/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at Packager.doBuild (/Users/hanwoongkim/elo/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/hanwoongkim/elo/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/hanwoongkim/elo/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/hanwoongkim/elo/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
    at Packager._build (/Users/hanwoongkim/elo/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/hanwoongkim/elo/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (/Users/hanwoongkim/elo/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/hanwoongkim/elo/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/hanwoongkim/elo/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/Users/hanwoongkim/elo/node_modules/electron-builder/src/cli/cli.ts:46:19)
```

**Comment by khw7096** [comment]
콤마를 지우고 npm install을 다시함. 됨.
