### ISSUE TITLE
npm start 시 에러 발생.

### ISSUE THREAD

**Issue by khw7096** [studio2l/elo#4]
```
npm http GET https://registry.npmjs.org/electron
npm ERR! Error: SSL Error: CERT_UNTRUSTED
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:525:26)
npm ERR!     at ClientRequest.g (events.js:193:14)
npm ERR!     at ClientRequest.EventEmitter.emit (events.js:93:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1461:7)
npm ERR!     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:111:23)
npm ERR!     at CleartextStream.socketOnData [as ondata] (http.js:1366:20)
npm ERR!     at CleartextStream.CryptoStream._push (tls.js:526:27)
npm ERR!     at SecurePair.cycle (tls.js:880:20)
npm ERR!     at EncryptedStream.CryptoStream.write (tls.js:267:13)
npm ERR!     at Socket.ondata (stream.js:38:26)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 18.5.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/woong/elo
npm ERR! node -v v0.8.10
npm ERR! npm -v 1.1.62
npm ERR! code ESSL
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/woong/elo/npm-debug.log
npm ERR! not ok code 0
```

**Comment by khw7096** [comment]
10.15.3 일 때는 에러가 발생하지 않는다.

**Comment by khw7096** [comment]
버전을 Readme에 명확히 표기함.
